# Generated by Django 5.1.3 on 2024-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('distribution_expense', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
